package com.saint.anthony.http;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class HttpApplication {

    public static void main(String[] args) {
        SpringApplication.run(HttpApplication.class, args);


    }

}

// servers eat a lot of RAM
// html generated by some stand alone server
// plugin json formatter - to install on chrome
// repository <-> service <-> controller -- correct
// homework - доробити домашку, то саме на кар, попрактикуватись...